### ISSUE TITLE
KF6

### ISSUE THREAD

**Issue by nclarius** [alex1701c/krunner-vscodeprojects#10]
I miss this plugin since I daily-drive Plasma 6; could you port it? I gave it a brief try but got lost in missing KF6 dependencies.

**Comment by alex1701c** [comment]
I need to give other runners of mine the same treatment. Hopefully I will have time this weekend 😅

**Comment by alex1701c** [comment]
Does the state of master work for you? I will only need like a dedicated install-qt6 script

**Comment by nclarius** [comment]
It installs but doesn't show up in my plugins list, and is not in effect.

**Comment by alex1701c** [comment]
You compiled from source with manual cmake options to use the -DBUILD_WITH_QT6 flag?

**Comment by nclarius** [comment]
> You compiled from source with manual cmake options to use the -DBUILD_WITH_QT6 flag?

No. When I tried just now, configuring failed:
```
 ***Unknown option --query
 CMake Warning at /usr/share/ECM/modules/ECMQueryQt.cmake:97 (message):
   Failed call: /usr/bin/qmake --query QT_INSTALL_PREFIX
 Call Stack (most recent call first):
   /usr/share/ECM/kde-modules/KDEInstallDirs6.cmake:199 (ecm_query_qt)
   /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:15 (include)
   CMakeLists.txt:14 (include)

 CMake Error at /usr/share/ECM/modules/ECMQueryQt.cmake:98 (message):
   Qt6 qtpaths call failed: 1
 Call Stack (most recent call first):
   /usr/share/ECM/kde-modules/KDEInstallDirs6.cmake:199 (ecm_query_qt)
   /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:15 (include)
   CMakeLists.txt:14 (include)

```

**Comment by alex1701c** [comment]
Please try a clean build :))

**Comment by nclarius** [comment]
> Please try a clean build :))

How is that done? I thought this amounts to removing CMake cache or the whole build dir but then I can't do ccmake? Can you tell me exactly the steps I need to do?

**Comment by alex1701c** [comment]
@nclarius Sorry, overlooked the mail. Clean uild means just cleaning the while build dir.

I have fixed the install.sh script now - can you try ;)

**Comment by nclarius** [comment]
Now it works :) Thank you
