### ISSUE TITLE
Install failed as krunner6

### ISSUE THREAD

**Issue by WizardMeow** [alex1701c/krunner-vscodeprojects#12]
https://github.com/alex1701c/krunner-vscodeprojects/blob/cb99fb64d04a40a8bcb684cc3e48e5f1179d4128/install.sh#L32

should this line use kquitapp6 when Plasma6 ?

**Comment by alex1701c** [comment]
it works when it is around. There has been a PR to adjust it and I have adapted the dependency list

**Comment by lokize** [comment]
![image](https://github.com/user-attachments/assets/68cf541b-cd7d-4af0-9ce4-8cdf96626df7)

error to installing here too

**Comment by alex1701c** [comment]
The provided error seems to be due to missing tooling - specifically the ld command
