### ISSUE TITLE
will this extension use git added projects?

### ISSUE THREAD

**Issue by ejnshtein** [alex1701c/krunner-vscodeprojects#5]
I discovered this awesome extension for krunner today, played a bit with it, and I have some questions and maybe proposals.

1. If you write a little bit more info about how this integration works in the readme it will be awesome.
  Currently, I had to dig into src to find why my projects aren't showing up in krunner.
  So yeah, if you add a link to [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager), which this extension uses, and tell that "you need to install it in order for this extension to work" that will be awesome.
2. I guess, no **plug n play** here?
  I really hope that after installing the vscode extension I wouldn't have to manually add every project that I work on to it's `projects.json`. Like a monkey, "click and save, click and save"...
  I see that **Project Manager** allows to specify where to look for git repositories and then it generates a `projects_cache_git.json` file with paths and projects names. It's just an array with "fullPath" and "name" variables, so maaaaaybe you can add support for it too? This will be awesome too!
3. How's the situation with native VSCode's "Recent Projects" list? Or there are problems retrieving this list in your plugin?

Thanks again!

**Comment by alex1701c** [comment]
>If you write a little bit more info about how this integration works in the readme it will be awesome.

Noted, will do!

>I guess, no plug n play here?

How do you mean that? Is it more about the extension in VScode than the KRunner plugin?

> It's just an array with "fullPath" and "name" variables, so maaaaaybe you can add support for it too? This will be awesome too!

Interesting! I will look into implementing this too. I have far more than 100 projects in my kde folder, so I might not be the targeted group :D

>How's the situation with native VSCode's "Recent Projects" list? Or there are problems retrieving this list in your plugin?

I think that would work. I remember looking into that quite some time ago, but looking again at the newly generated file it seems doable.

**Comment by alex1701c** [comment]
See https://github.com/alex1701c/krunner-vscodeprojects/commit/201c37c240fd35b7a7d7ec09ebeed25738349582

TBH I am wondering if there is even a need to select the custom file location. I will adjust the runner to use QStandardPaths which will make the search more robust and XDG conform.  
I think I wrote the config file in a time where I got overly excited to add config options xD

**Comment by ejnshtein** [comment]
Wow, cool!

**Comment by ejnshtein** [comment]
BTW, when we'll be able to test those changes?

I see that this package is uploaded to aur through this guys repo https://github.com/sergeyshevch/AUR but there weren't many updates since June 🤔

**Comment by alex1701c** [comment]
I don't maintain the AUR stuff, but this project has an install script which should work just as well :)

**Comment by ejnshtein** [comment]
okay!

**Comment by alex1701c** [comment]
@ejnshtein  Can you please check if it is working with latest master?

**Comment by ejnshtein** [comment]
![Screenshot_20211225_022637](https://user-images.githubusercontent.com/18352350/147374837-c0537c6b-5906-49a3-ad05-dca06a417e9d.png)

Well, looks like it does want some dependencies

**Comment by alex1701c** [comment]
Yeah, you need extra-cmake-modules

**Comment by ejnshtein** [comment]
okay, added this dependency on my manjaro system and it build just fine
and works just fine too

:+1:

**Comment by alex1701c** [comment]
Cool :)
