### ISSUE TITLE
This plugin does not work correctly with VSCodium.

### ISSUE THREAD

**Issue by sylvesterroos** [alex1701c/krunner-vscodeprojects#6]
I set the projects file to the correct path (`/home/sylvester/.config/VSCodium/User/globalStorage/alefragnani.project-manager/projects.json`) and the projects do show up in KRunner, however when I select them nothing happens. I'm assuming that this plugin is using the `code` binary to launch the project, but on VSCodium this should be the `codium` binary.

**Comment by alex1701c** [comment]
Yeah, makes sense. I will look into fixing it.

**Comment by alex1701c** [comment]
Can you please try out master and see if it works now as expected?

**Comment by sylvesterroos** [comment]
By using this command? `https://raw.githubusercontent.com/alex1701c/krunner-vscodeprojects/master/install-user.sh`, because the issue wasn't fixed when I the plugin using that script. I also tried the git aur package, where it also didn't work with codium

**Comment by alex1701c** [comment]
Classic case of forgetting to amend the latest little change :)

Please try with latest master

**Comment by sylvesterroos** [comment]
It now correctly launches the project using VSCodium. However there seems to be another issue, and I can't remember if this happened before as well. Some of my projects seem to be duplicated. I deleted all the items from my 'favorites' list and disabled/enabled VSCodeRunner just to be sure that that wasn't the issue, and it stopped showing duplicate items, proving that the 'favorites' list is the problem.
![image](https://user-images.githubusercontent.com/39904003/145364869-e97fb6ee-dfb0-49af-b4b6-90fb88513b66.png)

![image](https://user-images.githubusercontent.com/39904003/145364849-7964d1fd-027d-4ba2-8f5b-4d44d20077f6.png)

Also, while I have your attention, might I recommend that this plugin also uses the `Program launch {project}` naming from JetBrainsRunner? It makes searching for stuff quicker by showing all VSCode projects when I search for VSCode, instead of typing in the name of the project itself :)

**Comment by alex1701c** [comment]
>Some of my projects seem to be duplicated. 

That should be addressed with https://github.com/alex1701c/krunner-vscodeprojects/commit/30432a729bd3bc18dfe3555ae60eed3388f82a55. Could you please verify that it is working as expected?

>Also, while I have your attention, might I recommend that this plugin also uses the Program launch {project} naming from JetBrainsRunner?

Could you file a new issue for that? I am not super sure about it right now :)

**Comment by sylvesterroos** [comment]
> That should be addressed with 30432a7. Could you please verify that it is working as expected?

It's fixed now 👍

> Could you file a new issue for that? I am not super sure about it right now :)

Will do!
